In [10]:
#first way to solve

import numpy as np

def Gram_schmidt(arr):
    return_matrix = np.zeros_like(arr)
    for i in range(len(arr)):
        return_matrix[i] = arr[i]
        for j in range(i):
                return_matrix[i] = return_matrix[i] - (np.dot(arr[i], return_matrix[j]) / np.dot(return_matrix[j], return_matrix[j])) * return_matrix[j]
        distance = np.linalg.norm(return_matrix[i])
    return return_matrix

n = int(input())
m = int(input())
arr = np.array([])

for i in range(0, m):
    x = list(map(float, input().split()))
    if i == 0:
        arr = np.array(x)
    else:
        arr = np.vstack((arr, x))
new_vector = list(map(float, input().split()))
check = np.vstack((arr, new_vector))

augmented_matrix_rank = np.linalg.matrix_rank(check)
coefficients_matrix_rank = np.linalg.matrix_rank(arr)
print(augmented_matrix_rank)
print(coefficients_matrix_rank)
if(augmented_matrix_rank == coefficients_matrix_rank and coefficients_matrix_rank == m):
    print(Gram_schmidt(arr))
else:
    print(Gram_schmidt(np.vstack((arr, new_vector))))

3
3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#second way to solve

import numpy as np

def Gram_schmidt(arr):
    return_matrix = np.zeros_like(arr)
    for i in range(len(arr)):
        return_matrix[i] = arr[i]
        for j in range(i):
                return_matrix[i] = return_matrix[i] - (np.dot(arr[i], return_matrix[j]) / np.dot(return_matrix[j], return_matrix[j])) * return_matrix[j]
        distance = np.linalg.norm(return_matrix[i])
        return_matrix[i] /= distance
    return return_matrix
def in_subspace(arr, given_vector):
    check = Gram_schmidt(arr)
    coefficients = np.dot(new_vector, check.T)
    return np.allclose(np.dot(coefficients, check), new_vector)

n = int(input())
m = int(input())
arr = np.array([])

for i in range(0, m):
    x = list(map(float, input().split()))
    if i == 0:
        arr = np.array(x)
    else:
        arr = np.vstack((arr, x))
new_vector = list(map(float, input().split()))
check = np.vstack((arr, new_vector))


if(in_subspace(arr, new_vector)):
    print(Gram_schmidt(arr))
else:
    print(Gram_schmidt(np.vstack((arr, new_vector))))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
